// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKBmioKtp_jd2hKrG62MlVRPMT07Rk8Ls',
    appId: '1:689023568440:web:ea0a93e7662a658450b4cd',
    messagingSenderId: '689023568440',
    projectId: 'property-investment-anal-a3b3d',
    authDomain: 'property-investment-anal-a3b3d.firebaseapp.com',
    storageBucket: 'property-investment-anal-a3b3d.firebasestorage.app',
    measurementId: 'G-Z7ELES7G69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6U17TUWppFbwBwfABLFXkOTHpYW1fLu4',
    appId: '1:689023568440:android:c97c7f25d86ab29650b4cd',
    messagingSenderId: '689023568440',
    projectId: 'property-investment-anal-a3b3d',
    storageBucket: 'property-investment-anal-a3b3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv6O9zgLmfNwi_Nfr_a4WUB4Q8EoABDj4',
    appId: '1:689023568440:ios:fa86fbbbbeb3216850b4cd',
    messagingSenderId: '689023568440',
    projectId: 'property-investment-anal-a3b3d',
    storageBucket: 'property-investment-anal-a3b3d.firebasestorage.app',
    iosBundleId: 'com.example.propertyAnalyzerMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv6O9zgLmfNwi_Nfr_a4WUB4Q8EoABDj4',
    appId: '1:689023568440:ios:fa86fbbbbeb3216850b4cd',
    messagingSenderId: '689023568440',
    projectId: 'property-investment-anal-a3b3d',
    storageBucket: 'property-investment-anal-a3b3d.firebasestorage.app',
    iosBundleId: 'com.example.propertyAnalyzerMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKBmioKtp_jd2hKrG62MlVRPMT07Rk8Ls',
    appId: '1:689023568440:web:d101fc2aec19205750b4cd',
    messagingSenderId: '689023568440',
    projectId: 'property-investment-anal-a3b3d',
    authDomain: 'property-investment-anal-a3b3d.firebaseapp.com',
    storageBucket: 'property-investment-anal-a3b3d.firebasestorage.app',
    measurementId: 'G-Q5XRTR73TB',
  );
}
